% -------------------------------------------------------------------
%  Generated by MATLAB on 18-Jun-2015 10:38:51
%  MATLAB version: 8.3.0.532 (R2014a)
% -------------------------------------------------------------------
saveVarsMat = load('practise1.mat');

x = saveVarsMat.x; % <1x5000 double> too many elements

y = saveVarsMat.y; % <1x5000 double> too many elements

clear saveVarsMat;
